### ISSUE TITLE
Can't login with my seed (nspv remote rpc error: invalid request data)

### ISSUE THREAD

**Issue by tonymorony** [TokelPlatform/tokel_dapp#175] opened 2021-11-08 06:38 UTC
## Operation System

MacOS Big Sur 11.6

## Expected Behavior

Login into a wallet with my wif

## Current Behavior

I can't login with `Error: OP_RETURN dfb4a469958f55b54b34806b1838b8fea3675099 has no matching Address` / bitgo crash in the logs

Log: https://pastebin.com/1Ev5x2TQ

**Comment by piggydoughnut** [comment] 2021-11-08 06:57
Thank you for reporting the issue.

I think the actual issue that is preventing you from logging in is 

```
BITGO (WORKER -> [MAIN] -> RENDERER)
  {
    type: 'list_transactions',
    data: null,
    error: 'Error: nspv remote rpc error: invalid request data'
  }
  ```
  
  The `OP_RETURN` error is a bitgo log which tells us that we cannot read address from one of the transaction' scripts on your address.

**Comment by piggydoughnut** [comment] 2021-11-15 08:13
I cannot reproduce but I think this will be fixed with bitgo (nspv-js) update which is coming in the next release as @dimxy mentioned there were issues with connectivity and I suspect this is one of them. However not 💯 on this one.

**Comment by piggydoughnut** [comment] 2021-11-15 08:14
Will close this for now but feel free to re-open if the coming release does not fix it.

**Comment by tonymorony** [comment] 2021-11-23 11:35
Just tried 1.1.3 and still can't log in with my seed (infinity loading on "trying to connect to nspv...") 

https://pastebin.com/SupnxcvU

thought it might be related to UTXO amount so consolidated on a full node to single utxo on this address (didn't help):

```
./tokel-cli listunspent
[
  {
    "txid": "c8e32c4b85f7c3274b751c67f8ab16ed6b9e518b9c8e2c413f9de1368fec60d3",
    "vout": 0,
    "generated": false,
    "address": "RBcvRmozW7zBmdNkZbKd1FdV3t89pmr66E",
    "segid": 35,
    "amount": 0.00084008,
    "interest": 0.00000000,
    "scriptPubKey": "76a91419ab81981d05951b6536e926481dd0f5ffc7aca788ac",
    "rawconfirmations": 3,
    "confirmations": 1,
    "spendable": true
  },
  {
    "txid": "c8e32c4b85f7c3274b751c67f8ab16ed6b9e518b9c8e2c413f9de1368fec60d3",
    "vout": 1,
    "generated": false,
    "address": "RQ1mvCUcziWzRwE8Ugtex29VjoFjRzxQJT",
    "segid": 2,
    "account": "",
    "amount": 168562.71000000,
    "interest": 0.00000000,
    "scriptPubKey": "76a914a19f7aa254dced0a17920ab1c2acf698841f67f688ac",
    "rawconfirmations": 3,
    "confirmations": 1,
    "spendable": true
  }
]
```

**Closed** 2022-01-25 02:23 UTC
Labels: bug
